import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolveRelation,validateRelationCatalog,validateAssertion} from '../skills/woia-re-domain-contracts/scripts/contracts.mjs';
const root=new URL('../skills/woia-re-domain-contracts/',import.meta.url);const catalog=JSON.parse(readFileSync(new URL('references/logical-relations.json',root)));
test('exact 85 relations include ChargeAdjustment and preserve logical keys/owners',()=>{assert.equal(validateRelationCatalog().relations,85);assert.match(resolveRelation('ChargeAdjustment').dependency_note,/No usar como corrección/);for(const r of catalog.relations){assert.ok(r.candidate_keys);assert.ok(r.semantic_owner)}assert.equal(validateRelationCatalog().physical_5nf,'NOT_RUN')});
test('omission, duplication, ownership and grain drift rejected',()=>{for(const mutate of [r=>r.pop(),r=>r[0]=r[1],r=>r[0].semantic_owner='Finance',r=>r[0].fact_grain='changed']){const c=structuredClone(catalog);mutate(c.relations);assert.throws(()=>validateRelationCatalog(c))}});
test('unknown relation rejects; resolved copy cannot mutate canonical source',()=>{assert.throws(()=>resolveRelation('Unknown'));const r=resolveRelation('Subject');r.name='new';assert.equal(resolveRelation('Subject').name,'Subject')});
test('source evidence and accepted money distinct relation grains',()=>{assert.notEqual(resolveRelation('PaymentObservation').fact_grain,resolveRelation('Payment').fact_grain);assert.match(resolveRelation('Allocation').dependency_note,/corrección compensatoria/)});
test('E2E A B C stored with accountable owner and mandatory adverse cases, not executed',()=>{for(const name of ['sale','rental','property-management']){const t=readFileSync(new URL('evals/e2e/'+name+'/SPEC.md',root),'utf8');assert.match(t,/Mandatory adverse assertions/);assert.match(t,/Execution: NOT_RUN/);assert.match(t,/Accountable owner/)}const f=JSON.parse(readFileSync(new URL('evals/fixtures/synthetic.json',root)));assert.equal(f.synthetic,true);assert.equal(f.accepted_payment,false);assert.equal(f.settlement_delivery_implies_payout,false)});
const receipt={case_id:'A',actor:'operator',started_at:'2026-10-07T01:00:00Z',ended_at:'2026-10-07T01:01:00Z',candidate_manifest_digest:'a'.repeat(64),organization_configuration_digest:'b'.repeat(64),result:'NOT_RUN',evidence_refs:[]};
test('assertion receipt binds exact digests and cannot claim evidence-free PASS',()=>{assert.equal(validateAssertion(receipt).result,'NOT_RUN');assert.throws(()=>validateAssertion({...receipt,result:'PASS'}));assert.throws(()=>validateAssertion({...receipt,candidate_manifest_digest:'latest'}));assert.throws(()=>validateAssertion({...receipt,ended_at:'2020-01-01'}))});
